pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                    cd frontend
                    npm install

                    cd ..\\backend
                    npm install
                '''
            }
        }

        stage('Build Frontend') {
            steps {
                bat '''
                    cd frontend
                    npm run build
                '''
            }
        }

        stage('Backend Check') {
            steps {
                bat '''
                    cd backend
                    node --version
                    npm --version
                '''
            }
        }
    }

    post {

        success {
            bat '''
                if not exist "C:\\JenkinsFeedback" mkdir "C:\\JenkinsFeedback"

                echo.>> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Number: %BUILD_NUMBER% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Status: SUCCESS >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Project: SkillSwap >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Job Name: %JOB_NAME% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Jenkins Auto Trigger: SUCCESS >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
            '''
        }

        failure {
            bat '''
                if not exist "C:\\JenkinsFeedback" mkdir "C:\\JenkinsFeedback"

                echo.>> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Number: %BUILD_NUMBER% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Status: FAILURE >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Project: SkillSwap >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Job Name: %JOB_NAME% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Jenkins Auto Trigger: FAILED >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
            '''
        }
    }
}