pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Check') {
            steps {
                bat 'docker --version'
                bat 'docker compose version'
            }
        }

        stage('Build Docker Images') {
            steps {
                bat 'docker compose build'
            }
        }

        stage('Start SkillSwap') {
            steps {
                bat 'docker compose up -d'
            }
        }

        stage('Check Containers') {
            steps {
                bat 'docker compose ps'
            }
        }

        stage('Backend Health Check') {
            steps {
                bat 'curl http://localhost:5000/api/health'
            }
        }
    }

    post {

        success {
            bat '''
                if not exist "C:\\JenkinsFeedback" mkdir "C:\\JenkinsFeedback"

                echo.>> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Number: %BUILD_NUMBER% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Status: SUCCESS >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Project: SkillSwap >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Job Name: %JOB_NAME% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Docker Deployment: SUCCESS >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
            '''
        }

        failure {
            bat '''
                if not exist "C:\\JenkinsFeedback" mkdir "C:\\JenkinsFeedback"

                echo.>> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Number: %BUILD_NUMBER% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Build Status: FAILURE >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Project: SkillSwap >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Job Name: %JOB_NAME% >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo Docker Deployment: FAILED >> "C:\\JenkinsFeedback\\build-feedback.txt"
                echo ================================================ >> "C:\\JenkinsFeedback\\build-feedback.txt"
            '''
        }

        always {
            bat 'docker compose ps'
        }
    }
}